cam = 0
zbar_status = None
message = 'Get close QR code to cam'
last_message = 'Get close QR code to cam'
beginning_game = True
item = None
name = "hola"
change_item = True
game_points = 0
game_success = 0
game_fail = 0
game_objects = None
game_initialized = False
game_number_objects = -1
message_alert = "alert-info"
game_image = "/files/static/Who.png"
game_display = "none"
fail_flag = False

