# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='tracks_multimedia',
            field=models.ManyToManyField(to='appQRMusical.Multimedia'),
        ),
    ]
