# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0002_player_tracks_multimedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='tracks_multimedia',
        ),
    ]
