# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0003_remove_player_tracks_multimedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
