# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQRMusical', '0006_auto_20170903_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='players',
            field=models.ManyToManyField(blank=True, to='appQRMusical.Player'),
        ),
    ]
